import type { Product } from "./store"

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Athletic Shirt",
    price: 79.99,
    image: "/athletic-shirt.jpg",
    category: "Tops",
    rating: 4.8,
    reviews: 234,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Navy", "Gray"],
    description:
      "High-performance athletic shirt made from breathable moisture-wicking fabric. Perfect for workouts and casual wear.",
    inStock: true,
  },
  {
    id: "2",
    name: "Classic Crew Neck",
    price: 89.99,
    image: "/crew-neck-sweatshirt.jpg",
    category: "Tops",
    rating: 4.6,
    reviews: 156,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal", "Navy", "Cream", "Black"],
    description: "Comfortable and versatile crew neck sweatshirt. Great for layering or wearing on its own.",
    inStock: true,
  },
  {
    id: "3",
    name: "Performance Joggers",
    price: 99.99,
    image: "/joggers-pants.jpg",
    category: "Bottoms",
    rating: 4.7,
    reviews: 189,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Navy", "Olive"],
    description: "Premium joggers with tapered ankles and deep pockets. Perfect for workouts or casual outings.",
    inStock: true,
  },
  {
    id: "4",
    name: "Slim Fit Jeans",
    price: 109.99,
    image: "/slim-fit-jeans.png",
    category: "Bottoms",
    rating: 4.5,
    reviews: 312,
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Indigo", "Black", "Light Blue"],
    description: "Timeless slim fit jeans in premium denim. A wardrobe staple that works with everything.",
    inStock: true,
  },
  {
    id: "5",
    name: "Lightweight Hoodie",
    price: 119.99,
    image: "/hoodie-sweatshirt.jpg",
    category: "Tops",
    rating: 4.9,
    reviews: 428,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Navy", "White"],
    description: "Ultra-comfortable lightweight hoodie. Perfect for layering or wearing solo.",
    inStock: true,
  },
  {
    id: "6",
    name: "Running Shorts",
    price: 59.99,
    image: "/athletic-running-shorts.png",
    category: "Bottoms",
    rating: 4.4,
    reviews: 87,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Red"],
    description: "Lightweight and breathable running shorts with inner mesh. Ideal for active pursuits.",
    inStock: true,
  },
  {
    id: "7",
    name: "Premium Tee",
    price: 49.99,
    image: "/plain-white-tshirt.png",
    category: "Tops",
    rating: 4.6,
    reviews: 521,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Navy", "Gray", "Charcoal"],
    description: "Classic premium t-shirt. A versatile essential for any wardrobe.",
    inStock: true,
  },
  {
    id: "8",
    name: "Chino Pants",
    price: 89.99,
    image: "/chino-pants.png",
    category: "Bottoms",
    rating: 4.5,
    reviews: 203,
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Khaki", "Navy", "Olive", "Charcoal"],
    description: "Versatile chino pants perfect for casual or smart-casual occasions.",
    inStock: true,
  },
]
